### ISSUE TITLE
Creating compacting drawer with damaged hammer

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#39]
When creating Compacting Drawers you have to use 2 undamaged Forge Hammers. But when you craft it, the Forge Hammer loses one charge and can't be used for another crafting operation of another Compacting Drawer. I think the idea you had is that the hammer gets used completely in the crafting process instead of the hammer losing a single charge (has 80 charges in total). So the hammer can't be used for another Compacting Drawer, but still can be used to smash metal to plates. If the hammer is supposed to lose a single charge instead of being used completely, the drawers should be able to be crafted with a damaged hammer as well (which you can't right now).

**Comment by Drakma** [comment]
It's supposed to consume the hammer.  I'll take a look.  I'm hoping to resolve all of these issues next Wednesday
On Dec 25, 2016, at 2:21 PM, AstroxV <notifications@github.com<mailto:notifications@github.com>> wrote:

When creating Compacting Drawers you have to use 2 undamaged Forge Hammers. But when you craft it, the Forge Hammer loses one charge and can't be used for another crafting operation of another Compacting Drawer. I think the idea you had is that the hammer gets used completely in the crafting process instead of the hammer losing a single charge (has 80 charges in total). So the hammer can't be used for another Compacting Drawer, but still can be used to smash metal to plates. If the hammer is supposed to lose a single charge instead of being used completely, the drawers should be able to be crafted with a damaged hammer as well (which you can't right now).

**Comment by Drakma** [comment]
Fixed in latest
